name: build_docker

on:
 push:
   branches:
     - main
 release:
   types: [ created ]

jobs:
 build_docker:
   name: Build docker
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and push backend
       id: docker_build
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile-backend
         push: true
         platforms: linux/amd64,linux/arm64
         tags: |
           zhangjiashu/feishubot:${{ github.ref_name }}
           zhangjiashu/feishubot:latest

     - name : build and push frontend
       id: docker_build-frontend
       uses: docker/build-push-action@v4
       with:
            context: .
            file: ./Dockerfile-frontend
            push: true
            platforms: linux/amd64,linux/arm64
            tags: |
              zhangjiashu/feishubot-frontend:${{ github.ref_name }}
              zhangjiashu/feishubot-frontend:latest
